services:
  notety:
    build:
      context: .
      dockerfile: Dockerfile
    image: notety:latest
    container_name: notety
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      # Example placeholder for future environment-based config
      - NODE_ENV=production
    # Uncomment to enable live-reload-like behavior for Nginx (not needed for prod tests)
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    #   - ./dist/notety:/usr/share/nginx/html:ro
  # Optional: mount your own certs for LAN (server.crt and server.key)
  # volumes:
  #   - ./certs:/etc/nginx/certs:ro
