#!/usr/bin/env node

/**
 * Generate version.ts file with app version, git commit hash, and build timestamp
 * This script is run automatically during the prebuild step
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Read version from package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
const version = packageJson.version;

// Get git commit hash
let gitCommit = 'unknown';
try {
  gitCommit = execSync('git rev-parse HEAD', { encoding: 'utf-8' }).trim();
} catch (error) {
  console.warn('Warning: Could not get git commit hash:', error.message);
}

// Get build timestamp
const buildDate = new Date().toISOString();

// Generate TypeScript file content
const content = `/**
 * Auto-generated version information
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by scripts/generate-version.js
 */

export interface VersionInfo {
  version: string;
  gitCommit: string;
  buildDate: string;
}

export const versionInfo: VersionInfo = {
  version: '${version}',
  gitCommit: '${gitCommit}',
  buildDate: '${buildDate}',
};
`;

// Write to src/version.ts
const outputPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(outputPath, content, 'utf-8');

console.log(`✓ Generated version.ts`);
console.log(`  Version: ${version}`);
console.log(`  Commit:  ${gitCommit.substring(0, 7)}`);
console.log(`  Date:    ${buildDate}`);
