#!/usr/bin/env node
/*
 * Generates a version.ts file with build metadata that can be imported at runtime.
 * Strategy:
 *  - Use package.json version as base (semver)
 *  - Append short git commit hash if repository present
 *  - Include build timestamp (UTC) and optionally branch name
 */
const { execSync } = require("child_process");
const { writeFileSync, existsSync, mkdirSync } = require("fs");
const { join } = require("path");

const root = process.cwd();
const pkg = require(join(root, "package.json"));

function safeGit(cmd) {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return "";
  }
}

const commit = safeGit("git rev-parse --short HEAD");
const branch = safeGit("git rev-parse --abbrev-ref HEAD");
const now = new Date();
const iso = now.toISOString();
// Local build identifier (sortable) YYYYMMDDHHMMSSmmm (UTC)
const pad = (n, l = 2) => String(n).padStart(l, "0");
const buildId = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(
  now.getUTCDate()
)}${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(
  now.getUTCSeconds()
)}${pad(now.getUTCMilliseconds(), 3)}`;

// Compose version: base semver + commit (if present) + timestamp build id
let version = pkg.version || "0.0.0";
version += "+" + (commit ? `${commit}.` : "") + buildId;

const content = `// Auto-generated by scripts/generate-version.cjs – DO NOT EDIT
// Generated: ${iso}
// Branch: ${branch}
// Commit: ${commit}
export const APP_VERSION = '${version}';
export const BUILD_COMMIT = '${commit}';
export const BUILD_BRANCH = '${branch}';
export const BUILD_TIME_UTC = '${iso}';
`;

const targetDir = join(root, "src", "environments");
if (!existsSync(targetDir)) mkdirSync(targetDir, { recursive: true });
const targetFile = join(targetDir, "version.ts");
writeFileSync(targetFile, content, "utf8");
console.log(`Generated ${targetFile}: ${version}`);
